config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/play', to: 'games#play'
  post '/play', to: 'games#play'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'open-uri'

ALPHABET = [
  %w[A E I L N O R S T U] * 10,
  %w[D G] * 9,
  %w[B C M P] * 8,
  %w[F H V W Y] * 7,
  %w[K] * 6,
  %w[J X] * 3,
  %w[Q Z]
].join.chars

VOWEL = %w[A E I O U].freeze

class GamesController < ApplicationController
  def play
    @data = JSON.parse(URI.open("https://wagon-dictionary.herokuapp.com/#{params['word']}").read)
    @grid = generate_grid(10)
    @score = params['score']&.to_i || 0
    @turns_left = params['turns_left']&.to_i || 5
    score if params['word']
  end

  private

  def score
    time_end = Time.now
    total_time = time_end - params['time_start'].to_datetime
    @round_score = word_validation? ? (@data['length'] * 100) / total_time : 0
    @score += @round_score.floor
    @turns_left -= 1
  end

  def enough_vowels?(grid_array)
    grid_array.any? { |letter| VOWEL.include?(letter) }
  end

  def enought_consonant?(grid_array, grid_size)
    VOWEL.map { |letter| grid_array.count(letter) }.reduce(:+) <= (grid_size / 2)
  end

  def generate_grid(grid_size, grid_array = [])
    until enough_vowels?(grid_array) && enought_consonant?(grid_array, grid_size)
      grid_array = []
      grid_size.times { grid_array << ALPHABET.sample }
    end
    grid_array
  end

  def word_validation?
    if @data['found'] && in_grid?
      @message = 'Good job!'
      true
    else
      @message = 'Invalid word :('
      false
    end
  end

  def in_grid?
    grid = params['grid'].split(',')
    params[:word].upcase.chars.all? do |letter|
      grid.count(letter) >= params[:word].upcase.count(letter) && grid.include?(letter)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/play.html.erb
<% if @turns_left > 0 %>
  <ul>
    <%  @grid.each do |letter| %>
      <li><%= letter %></>
    <% end %>
  </ul>

  <form name="game" method="post" action="/play">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input name="utf8" type="hidden" value="&#x2713;" />
  <input name="time_start" type="hidden" value="<%= Time.now %>" />
  <input name="score" type="hidden" value="<%= @score %>" />
  <input name="turns_left" type="hidden" value="<%= @turns_left %>" />
  <input name="grid" type="hidden" value="<%= @grid.join(',') %>" />
  <input id="word" name="word" type="text" placeholder="Find the longuest word you can."/>
  <input id="submit" name="submit" type="submit" value="Search"/>
  <body OnLoad="document.game.word.focus();">
  </form>

  <h2>Your score: <%= @score %> points</h2>
  <h3>Turns left : <%= @turns_left %></h3>
  <% if @round_score %>
    <p><%= @message %> | You scored <%= @round_score.floor %></p>
  <% end %>

<% else %>
  <ul>
    <% ['G', 'A', 'M', 'E', '', '', 'O', 'V', 'E', 'R'].each do |letter| %>
      <li><%= letter %></>
    <% end %>
  </ul>

  <h2>Your finale score: <%= @score %> points</h2>
  <%= link_to 'Retry?', play_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <h1>The longuest word game</h1>
      <%= yield %>
    </div>
  </body>
</html>